name: Run SabziU Bots

on:
  push:
  workflow_dispatch:

jobs:

  telegram-bot:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Telegram bot
        run: |
          python bot.py


  bale-bot:
    runs-on: ubuntu-latest

    env:
      BALE_BOT_TOKEN: ${{ secrets.BALE_BOT_TOKEN }}
      BALE_ADMIN_CHAT_IDS: ${{ secrets.BALE_ADMIN_CHAT_IDS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Check Bale Version
        run: |
          pip show bale
          python -c "import bale; print('BALE PATH:', bale.__file__)"

      - name: Test connection to Bale
        run: |

      - name: Test connection to Bale
        run: |
          echo "Testing connection to tapi.bale.ai..."

          for i in 1 2 3 4 5
          do
            echo "Connection attempt $i..."

            if curl -I --connect-timeout 15 --max-time 30 https://tapi.bale.ai
            then
              echo "Bale server is reachable."
              break
            fi

            if [ "$i" -eq 5 ]
            then
              echo "Bale server could not be reached after 5 attempts."
              exit 1
            fi

            echo "Connection failed. Waiting 10 seconds before retry..."
            sleep 10
          done

      - name: Run Bale bot
        run: |
          python -u bale_bot.py
