name: Run SabziU Bots

on:
  push:
  workflow_dispatch:

jobs:

  telegram-bot:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Telegram bot
        run: |
          python bot.py


  bale-bot:
    runs-on: ubuntu-latest

    env:
      BALE_BOT_TOKEN: ${{ secrets.BALE_BOT_TOKEN }}
      BALE_ADMIN_CHAT_ID: ${{ secrets.BALE_ADMIN_CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bale bot
        run: |
          python bale_bot.py
